### ISSUE TITLE
Empresa kloud cometendo os mesmo erros do mundo real?

### ISSUE THREAD

**Issue by nicholasess** [training-center/hiring-center#10]
## Sobre a vaga

Galera, as vagas estão superficiais demais, como posso me candidatar a uma vaga que não diz quais são as tecnologias que serão usadas? Me pareceu enunciado de prova da faculdade.
Além disso, não diz sobre ser CLT ou PJ, presencial ou remoto, valor do salário, onde a empresa reside, quais são os beneficios, horário de trabalho. E ficou estranho o fullstack com back end pleno e front end pleno fazendo praticamente as mesmas tarefas, o que mudaria no dia a dia? Acredito que só o salario em si.

Um tempo atrás eu criei esse readme.md, acredito que pode ser a forma de montar a vaga

#### Descreva a empresa

Um storytelling sobre a empresa, como funciona internamente, localização e horário de trabalho.

#### Descreva a Vaga

Descreva a vaga em si, colocando as tecnologias que o desenvolvedor irá trabalhar no dia a dia, além de:
- Precisa estar formado? Se sim, adicione os cursos.
- É CLT ou PJ?
- Salário a combinar? Caso não seja, informe a faixa salarial.
- Alocado ou Remoto?

#### Requisitos

Adicione em lista, as tecnologias que são indispensáveis.

#### Desejaveis 

Além dos requisitos, liste outras tecnologias que são estrelinha no caderno.

#### Beneficios 

Sabendo de tudo o que solicitam, descreva o que o desenvolvedor ganhará, caso esteja no time.

@rafaels88

**Comment by renesoaresse** [comment]
Concordo com o @nicholasess, ficou bem genérico. Parabéns por levantar esses pontos.

**Comment by WendellAdriel** [comment]
A ideia que foi discutida no canal era justamente as vagas serem genéricas.
O que acham @training-center/hiring-center????

**Comment by rafaels88** [comment]
Que ótimos pontos levantados, @nicholasess! Muita dessas coisas tinha sequer passado pela minha cabeça, mas vamos lá, vou dar minha opinião:

* Descreva a empresa - foi ótimo você levantar esse ponto, eu, @WendellAdriel e todo o time do HC começamos a discutir essa necessidade hoje pela manhã, e vamos melhorar o storytelling da empresa que temos e nos preocupar sobre as futuras. Também estamos sentindo falta.

* Descreva a vaga - estes quatro pontos que você citou não passou pelas nossas conversas, imagino que justamente por ser apenas uma simulação. Claro que podemos adicionar estes itens caso eles adicionem valor pro candidato que está lendo. Você imagina que estes itens adicione valor a entrevista? Por exemplo, de repente a oportunidade de haver um pedido de negociação e esse pedido ser avaliado posteriormente pelo HC? Meu medo de adicionar estes itens é eles afastarem alguém de fazer a entrevista porque colocamos na vaga que será PJ mas a pessoa só faria se fosse CLT, quando na verdade tanto faz, a pessoa não será contratada de verdade de qualquer forma.

* Requisitos - nós não queremos limitar a tecnologia que o candidato deve saber atualmente. Se ele souber C++ ou Python, pro HC tanto faz, os testes e entrevistas não serão limitados a esse nível. O que podemos fazer aqui é adicionar as tecnologias que a empresa trabalha atualmente, mas deixar claro que a pessoa não precisa ter experiência prévia em nenhuma das tecnologias utilizadas atualmente pela empresa, o que acha? Faz sentido?

* Desejaveis -  repito aqui o que disse no item acima. O que acha?

* Beneficios - acabo caindo nos mesmos argumentos acima. Será que alguém deixará de se candidatar à simulação da vaga porque os benefícios não são bons o suficiente? Se sim, isso seria horrível. A pergunta aqui é, qual valor essa informação pode trazer as entrevistas? Me diga se você encontrar, isso realmente me interessa.

**Comment by rafaels88** [comment]
@WendellAdriel se sinta a vontade pra discordar de tudo o que eu disse :P

**Comment by renesoaresse** [comment]
@rafaels88 não tinha pensando a respeito sobre os itens de requisitos, desejáveis e benefícios, faz muito sentido o que você falou. Porém é relevando o ponto de alocado ou remoto, tanto para o entrevistado para o entrevistador. Não seria interessante colocar no assunto do e-mail se será alocado ou remoto?

**Comment by WendellAdriel** [comment]
Desculpem pela minha resposta curta anteriormente, estava com muito trabalho aqui 😋 
Agora consigo falar melhor:

- Sobre a descrição da empresa eu concordo que devemos melhorar e detalhar mais para que haja mais conteúdo e mais informações.

- Sobre os pontos destacados na descrição da vaga, não vejo que esses itens sejam essenciais para uma simulação. Saber se precisa ser formado, CLT ou PJ, remoto ou presencial, faixa salarial. Todas essas informações fogem do escopo do projeto que é: **treinar para processos seletivos**

- Sobre os requisitos, de momento não queremos e nem temos recursos suficientes para fazer testes focados em N tecnologias, por isso no começo pensamos em fazer um processo mais neutro, ou seja, vai ser cobrado que você saiba os assuntos pertinentes, porém você pode resolver utilizando qualquer linguagem e tecnologia que quiser. Quando o projeto crescer e tivermos mais recursos podemos pensar em criar vagas para tecnologias específicas, mas por agora creio que não seja algo prioritário.

- Sobre os desejáveis minha opinião é a mesma sobre os requisitos

- Sobre os benefícios minha opinião é a memsa sobre a descrição da vaga, são informações que fogem do escopo do projeto.

**Comment by rafaels88** [comment]
@nicholasess e @renesoaresse podem dar uma lida no PR referenciado aqui em cima e ver se faz sentido isso pra vocês?

**Comment by nicholasess** [comment]
Vocês vão preparar um material para ajudar as pessoas, explicando a diferença entre CLT x PJ? Só indiquei a forma de contratação para ajudar os entrevistados a tomar decisão. Mesmo que seja um processo seletivo, tudo o que possa ser ensinado aos novatos, é bem vindo.

**Comment by nicholasess** [comment]
Agora surgiu a dúvida, se a tecnologia pouco importa, como será a parte de teste? @rafaels88 
Não adianta o cara saber PHP e o entrevistador souber somente NodeJs. Aí ele pede em nodejs e o entrevistado não pode prosseguir por causa do knowhow. Como fará nessa situação?

**Comment by rafaels88** [comment]
> Vocês vão preparar um material para ajudar as pessoas, explicando a diferença entre CLT x PJ

Cara, acho que não. Essa não é a intenção do projeto. O foco é fazer as entrevistas e dar feedback sobre elas, e não responder todas as perguntas sobre contratações e como conseguir empregos, sabe? Tem muito material sobre isso na internet, inclusive. Acho que a gente produzir algo assim seria mais do mesmo. Mas claro, se perguntarem a gente vai responder =)

> se a tecnologia pouco importa, como será a parte de teste?

Concordo, nessa tua situação aí iria dar ruim haha
Olha, eu já participei de uns 20 processos seletivos na vida como candidato, e em alguns deles a tecnologia que eu iria usar para resolver o teste não importava. Também já entrevistei candidatos e os testes permitiam as pessoas fazer em qualquer linguagem. Recebemos respostas em C#, Python, Ruby... o importante é entender a lógica e o algoritmo. Creio que todas as linguagens mais populares são fáceis de ler e entender a lógica ali. Em todo caso, quando ocorre uma situação em que o entrevistador não entende certa parte do código, é uma boa oportunidade para pedir ao candidato explicar.

Creio que nessa situação específica quem tem que se virar nos 30 é o entrevistador, não o candidato =)

Faz sentido?

**Comment by nicholasess** [comment]
Bom, vendo por esse lado de se virar nos 30, não me deixaria confortável para ser um entrevistador. Essa sensação de ter que remediar um processo que poderia ser evitado, caso houvesse no enunciado as tecnologias que seriam utilizadas... Mas sem problemas, espero que os entrevistadores estejam cientes quando forem convidados.

Obrigado por esclarecer @rafaels88 

Fecharei a Issue!
