### ISSUE TITLE
Como será o processo para o candidato enviar o curriculo?

### ISSUE THREAD

**Issue by rafaels88** [training-center/hiring-center#2]
Perguntas que precisamos responder:
  1. O candidato enviará um documento (curriculo) ou criará um repositório para o seu CV e enviará o link para o repositório (esta segunda opção pode ser um empecilho para pessoas que não sabem mexer com git);

  1. Depois de pronto o currículo, como o candidato enviará este curriculo para concorrer a vaga?

**Comment by dyhalmeida** [comment]
Acredito que criando um repositório do currículo será mais eficiente, ou seja, elaborar um currículo em um repositório [curriculo/README.md], no qual dentro do arquivo README.md será escrito o currículo. E para concorrer a entrevista, poderá abrir uma issue padronizada com o link, no repositório do projeto.

**Comment by erickluz** [comment]
Na minha opnião, via repositório, ja vi empresas como a Globo por exemplo, utilizando esse método.

**Comment by crisgon** [comment]
Ou poderia criar uma pasta Currículos aqui no próprio repositório. 
O candidato faz o fork, adiciona o currículo.md na pasta e manda um pull request pra finalizar o processo.

**Comment by alinebastos** [comment]
Gostei da ideia do @crisgon, mas ao mesmo tempo me preocupa quem não sabe mexer no git/github.

**Comment by alinebastos** [comment]
Porque uma coisa que é importantíssima nesse processo é o currículo da pessoa, que geralmente é em doc ou pdf. A primeira parte do processo é avaliação do curriculo, e, se a pessoa não passar nessa fase, receberá o feedback sobre o curriculo. Então acho que o ideal seria o curriculo não ser em .md, e sim anexar o doc ou pdf mesmo.

**Comment by alinebastos** [comment]
Não seria interessante essa parte também ser privada como o resto do processo? A pessoa mandar o curriculo pra gente de alguma forma que não seja o github? Tem gente que pode se sentir intimidado, além do caso de quem não sabe usar a plataforma.

**Comment by alinebastos** [comment]
Posso ver com o @woliveiras de criar um e-mail do TC onde os recrutadores vão ter acesso.

**Comment by crisgon** [comment]
Verdade, bem melhor mandar algo privado do que ficar recebendo um monte de pitaco que pode acabar confundindo. Não que receber opiniões seja ruim, mas além de sentir vergonha de colocar o curriculo publico a pessoa pode desanimar quando receber algum feedback de alguém que não sabe se expressar de forma delicada.
**Pelo visto a solução vai ser o bom e velho e-mail.**

**Comment by rafaels88** [comment]
Eu gosto bastante do email tbm!

**Comment by erickluz** [comment]
Compreendo plenamente com o constrangimento de colocar o currículo de forma publica, posso ter entendido errado, mas acredito a ideia aqui, é receber criticas sim, boas ou ruins eu particularmente, tenho muita duvida de como montar um currículo de ótima qualidade. Qualquer critica pra mim é uma vantagem. Tenho MUITA vontade também de comparar o meu currículo com os de outros profissionais, para ver que eu possa ter esquecido de ter colocado, pontos inúteis, e pontos cruciais.

**Comment by alinebastos** [comment]
Na verdade o objetivo do projeto é receber um feedback oficial, como se fosse uma empresa avaliando um candidato.
Então o ideal é que seja privado esse processo.
Temos o canal #prep-entrevistas lá no slack justamente pra todos tirarem qualquer tipo de duvidas, sobre curriculo, sobre entrevistas, etc. Quem quiser pode jogar o curriculo lá e pedir feedback :)

**Comment by rafaels88** [comment]
@alinebastos Sabe se o email do TC vai rolar? Se não a gente pode criar um outro email do gmail notmal tbm pra ser um alias pros entrevistadores.

**Comment by alinebastos** [comment]
Tô vendo aqui com o Will, mas se não me engano eu usei o gmail mesmo pra fazer o e-mail de uma outra iniciativa.

**Comment by alinebastos** [comment]
Vai ser pelo gmail, o TC não tem e-mail pelo dominio.

**Comment by rafaels88** [comment]
Bem, dá pra fazer um redirect de graça pelo Mailgun usando o domain do TC :p Mas se for dar mt trabalho, vamos de gmail mesmo =)

**Comment by rafaels88** [comment]
Email criado e adicionado no Readme.
