### ISSUE TITLE
Como o candidato poderá ver os horários disponíveis para agendar uma entrevista?

### ISSUE THREAD

**Issue by rafaels88** [training-center/hiring-center#3]
Cada empresa tem seus entrevistadores e cada entrevistador deve disponibilizar os horários em que ele pode entrevistar o candidato. Logo:

  1. Onde ficará estes horários? Numa espécie de agenda virtual?
  1. O candidato vai escolher um horário vago e irá se candidatar? Como será isso na prática?

**Comment by vcapretz** [comment]
a ideia de usar o [Calendly](https://calendly.com/) é bem boa, mas ai o candidato primeiro se aplica e quem for responsável por entrevistá-lo pode enviar o link da agenda, e o candidato escolhe

**Comment by rafaels88** [comment]
Isso! Eu me esqueci de escrever sobre esse processo. O candidato só poderia escolher um horário depois de ter o CV aprovado. Vou escrever isso lá no Readme.

Eu nunca usei o Calendly, mas gostei bastante da ideia. Mas tu sabe se ele se integra bem com os devices como o Google Agenda, ou eu tenho que baixar uma app só dele pra ser lembrado de que vou ter uma entrevista daqui a 1h, por exemplo? Senão vou acabar tendo q cadastrar um evento no meu GAgenda tbm haha

**Comment by alinebastos** [comment]
O ideal é ocorrer como um processo normal, a unica diferença é que sempre será online.
Depois que o candidato é selecionado pelo curriculo o entrevistador vai marcar um dia e um horário com o candidato via e-mail, normalmente, como em um processo normal. Pode ser via aplicativo de calendário, pode ser manualmente mesmo, os dois concordando com um horário, isso não precisa necessariamente ter uma maneira pre-definida, até pq num processo real o candidato segue as regras daquela seleção.

**Comment by vcapretz** [comment]
@rafaels88 quando vc escolhe uma data na agenda de alguém vc coloca seu email e ele envia um invite para os dois! então vc pode usar seu calendário usual tranquilamente, a ferramenta só ajuda a mostrar quais são as opções 😄

**Comment by rafaels88** [comment]
@alinebastos Eu gosto muito dessa forma flexível de operar o projeto. Concordo com você, acho que isso pode ficar a cargo do próprio processo entre aquele entrevistador e o entrevistado.

@vcapretz Cara, eu amei a ferramenta. Eu acho que podemos criar (em breve) um documento destinado aos entrevistadores para ajudar com dicas e ferramenta a serem usadas nos processos. E aí podemos indicar o Calendly como ferramenta pra agendar o compromisso com o candidato, o que acha? (@alinebastos , faz sentido?)

**Comment by vcapretz** [comment]
acho que faz sentido sim!! algumas delas (por exemplo o zoom) podem exigir que algum download seja feito, então é bom deixar o setup sempre pronto!

**Comment by rafaels88** [comment]
Fechando a issue, já que definimos que isso será flexível e definido com o próprio candidato quando recebermos o CV e enviamos uma resposta positiva.

Mais para frente podemos definir um padrão, mas isso pode ser um processo mais interno.
