### ISSUE TITLE
Quais serão as empresas fictícias?

### ISSUE THREAD

**Issue by rafaels88** [training-center/hiring-center#4]
Cada empresa deverá ter:

  * Nome;
  * Breve descrição;
  * Vagas disponíveis;
    * Nome (ex.: dev backend, fullstack...)
    * Nível técnico (ex.: estagiário, pleno ...);
    * Requisitos

É importante que as vagas e a descrição da empresa especifiquem o menos possível a linguagem (se possível sequer citar isto), para que a entrevista possa servir para desenvolvedores de qualquer linguagem que se encaixe com o perfil da vaga.

**Comment by crisgon** [comment]
Não seria mais simples ter uma única empresa fictícia com várias vagas disponíveis? Pra diversos níveis e funções? Acho que seria mais tranquilo de gerenciar.

**Comment by rafaels88** [comment]
@crisgon Acho que dependendo da empresa, não tem como ela ter vaga para uma pessoa que quer simular uma entrevista com algoritmos mais arrojados e outra que quer apenas um processo de construir um visual site. Por exemplo: uma consultoria que desenvolve ecommerces, blogs e sites para empresas tem profissionais mt diferentes de um marketplace com 50 milhões de requisições por mês. Mesmo se tratando do mesmo nível de dev, o perfil que estas empresas procurariam é muito diferente. O que acha?

**Comment by crisgon** [comment]
Entendi. Realmente, o perfil de um front end jr será diferente em cada realidade.

**Comment by rafaels88** [comment]
Creio que o desafio aqui é criar o mínimo de empresas possíveis que englobe o máximo de perfis possíveis. Eu não gostaria que passasse de três empresas. Se puder ser duas, melhor ainda. Mas não gostaria de deixar ninguém de fora.

Talvez, a melhor forma de responder isso seja mapeando os perfis de programadores mais comuns e a partir disso criar empresas que englobem eles, o que acha?

**Comment by rafaels88** [comment]
Fechando essa issue já que estamos já criando as empresas. Podemos criar uma issue ou PR separado para discutir a criação de uma nova empresa se for o caso.
