### ISSUE TITLE
Como serão as entrevistas?

### ISSUE THREAD

**Issue by crisgon** [training-center/hiring-center#7]
### Seria bom ir pensando nessas coisas pra deixar disponível logo no README
- As entrevistas vão ser online? 
- Utilizando que plataforma? 
- E como será feito os testes práticos?

**Comment by rafaels88** [comment]
Ótima Issue, @crisgon ! Vou responder de acordo com o que pensei até agora:

> As entrevistas vão ser online?

Sim, isso eliminaria um bloqueio enorme que seria a presença do entrevistado e entrevistador no local. Acho que tornaria este projeto inviável, inclusive.

> Utilizando que plataforma?

Creio que a plataforma pode ser sugeria inicialmente pelo entrevistador, mas se por algum motivo o candidato não puder utilizá-la, eles podem combinar outra forma que seja viável para aquele teste (que no caso vai ser definido pelo entrevistador). Isso acontece em muitas empresas. Resumindo, acho que está é uma questão flexível.

> E como será feito os testes práticos?

Isso também não tem resposta fixa. Depende do teste que vai ser aplicado e o teste será definido pelo entrevistador. Assim como quando você faz entrevista para duas empresas diferentes os testes são conduzidos de forma diferentes utilizando plataformas diferentes, aqui também vai depender da situação. Até porque não acredito que os testes serão sempre iguais. A criatividade dos entrevistadores vai alterar esse cenário sempre. Claro que idealmente de forma que o teste seja possível de ser efetuado.

Faz sentido?

**Comment by rafaels88** [comment]
Vou adicionar essas informações ao README. Se as informações ficaram claras, fique a vontade para fechar a Issue. Se não, vamos continuar discutindo por aqui =)
