### ISSUE TITLE
Entrevistas em Inglês

### ISSUE THREAD

**Issue by nicholasess** [training-center/hiring-center#8]
Trabalhar fora também é um sonho de muitos por aqui, seria legal se tivesse empresas fictícias estrangeiras com entrevistas em inglês

**Comment by rafaels88** [comment]
Obrigado pela issue, @nicholasess ! Essa ideia tá no plano inicial do projeto mas eu me esqueci completamente de adicionar isso no Readme. A ideia é que o candidato escolha se quer fazer a entrevista em inglês ou português.

Vou adicionar lá no Readme em breve e venho aqui atualizar a Issue!

Obrigado!

**Comment by alinebastos** [comment]
Eu já acho que podem ter vagas em ingles e vagas em portugues. Não acho legal o candidato escolher pq nem todos os entrevistadores saberiam levar uma entrevista em inglês.
Na vaga pode constar que pode ser em inglês ou portugues. Cada entrevistador que decide isso isso na vaga que ele criar, o que acham?

**Comment by rafaels88** [comment]
Na verdade, eu tava pensando que cada vaga pode ter diferentes entrevistadores. No caso, o entrevistador estaria vinculado mais a empresa/empresas do que a vaga em si. E no caso, se o candidato mandar o CV e disser que quer entrevista em inglês, seria uma questão dos entrevistadores daquela empresa se organizarem pra ver quem vai entrevistar. (No caso, seria assim com todas as vagas, o que me parece algo tão rápido quanto um entrevistador ir lá no canal do slack e falar que vai entrevistar aquele candidato tal, pra nao correr o risco de ngm fazer o mesmo).

Faz sentido?

**Comment by nicholasess** [comment]
No mundo real, as vagas em inglês não dão opções para o entrevistado escolher, ele já está se candidatando sabendo que essa é a regra. Acredito que é essa a intenção do projeto, vivenciar e extrair ao máximo uma entrevista de emprego. Sendo assim, o candidato envia o cv para vaga que ele se encaixa.

**Comment by rafaels88** [comment]
Mas ao mesmo tempo seria legal flexibilizar as oportunidades pras pessoas poderem simular a situação que elas estão prestes a passar, não? Digo, se **Empresa X** tem uma vaga pra Junior Fullstack em Inglês, por que não podemos disponibilizar essa vaga em Português tbm pra quem quiser poder treinar? Digo, assim a gente engloba o máximo possível de situações.

Tem pessoas que não querem treinar entrevista em inglês e tem gente que precisa muito treinar inglês. E as vezes a mesma vaga pode agregar as duas pessoas, o que acha?

**Comment by nicholasess** [comment]
Bom, português é padrão, então coloca como opção a entrevista somente inglês, mas quem adiciona a opção, é a empresa com seus entrevistadores.
Flexibilidade é importante, só fica bagunçado quando da essa tomada de decisão ao entrevistado.
Seria assim: Candidato encontra uma vaga e manda o cv com a opção que ele quer: PT ou EN. Dali em diante, o processo de avaliação + feedback, será no idioma que escolheu.

Que tal?

**Comment by rafaels88** [comment]
Isso, exatamente o que eu pensei :) O candidato aplicaria pra vaga dizendo a lingua. A partir dai é sempre naquela lingua, toda conversa, entrevista, feedback... É como se desse a escolha pro candidato "configurar" a simulação que ele vai passar no inicio.

É isso que você quiser dizer?

**Comment by nicholasess** [comment]
Show @rafaels88, sucesso no projeto galera.

**Comment by rafaels88** [comment]
Obrigado pela contribuição, @nicholasess ! Lembrando que quando quiser se juntar ao time de entrevistadores é só avisar! :D Vai ser muito bem vindo!

**Comment by nicholasess** [comment]
Agradecido pelo convite @rafaels88

**Comment by rafaelmaruta** [comment]
perfeito, preciso treinar entrevistas em inglês para oportunidades lá fora =)

**Comment by rafaels88** [comment]
Adicionei as informações lá no Readme. Se estiver de acordo fique a vontade para fechar a Issue. Se não, fique a vontade para levantar os pontos aqui até a gente chegar num ponto ótimo! ;)

**Comment by nicholasess** [comment]
@rafaels88 beleza

**Comment by nicholasess** [comment]
@rafaels88 o readme está vazio

**Comment by rafaels88** [comment]
@nicholasess Perdão, eu deveria ter sido mais específico! Adicionei no PR do Readme que ainda está em revisão. Linkei o PR a esta issue para ficar mais fácil. ;)

**Comment by rafaels88** [comment]
Fechando esta issue, já que a informação está contida no Readme atual.
